# Generated by Django 4.0.5 on 2022-06-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_contato_mostrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='data_criacao',
        ),
    ]
