# Generated by Django 4.0.5 on 2022-06-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_contato_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d'),
        ),
    ]
